terraform {
  required_providers {
    spacelift = {
      source  = "spacelift-io/spacelift"
      version = "~> 1.0"
    }
  }
}

# Configure the Spacelift Provider
# Uses spacectl authentication automatically
provider "spacelift" {
  # The provider will automatically use spacectl's stored credentials
  # No additional configuration needed when using spacectl
}

resource "spacelift_space" "poc_space" {
  name                = "POC Environment"
  description         = "Space for POC testing and demonstrations"
  inherit_entities    = false
  parent_space_id     = "root"

  labels = [
    "environment:poc",
    "purpose:testing"
  ]
}

# Create a worker pool for the POC
resource "spacelift_worker_pool" "poc_pool" {
  name        = "poc-local-k8s-pool"
  description = "Local Kubernetes worker pool for POC testing"
  space_id    = spacelift_space.poc_space.id
  
  # Read the CSR from the file generated by our script
  csr = filebase64("../certs/spacelift.csr")
  
  # Optional: Associate with a specific space
  # space_id = spacelift_space.poc_space.id
  
  labels = [
    "environment:poc",
    "type:local",
    "platform:kubernetes"
  ]
}

output "worker_pool_config" {
  value = spacelift_worker_pool.poc_pool.config
  sensitive = true
}

